### ISSUE TITLE
weird issue on shift+t, possibly crossmod

### ISSUE THREAD

**Issue by Yoghurt4C** [CottonMC/MetaTips#2]
https://pastebin.com/U07db1da

**Comment by LemmaEOF** [comment]
Can you ID a specific item that did this?

**Comment by Yoghurt4C** [comment]
happens on trying to link any item

**Comment by LemmaEOF** [comment]
It looks like it's a crossmod thing, since it's happening in the `ChatListenerHud`, which my mod doesn't touch. I'm using the vanilla code to convert an ItemStack to a text component, so someone whose mod is messing with the chat hud isn't properly built for that, which means there's likely other incompatibilities they have too.

**Comment by Yoghurt4C** [comment]
turns out that [Ping](https://minecraft.curseforge.com/projects/word-ping) is the culprit
